#include <windows.h>
#include <ddraw.h>
#include <scrnsave.h>
#include "Alchemy.h"
#include "JPEGUtil.h"
#include "DirectXUtil.h"
#include "Resource.h"
#include "..\TSE\TSE.h"
#include "..\TSUI\TSUI.h"
#include "TransSaver.h"